// <auto-generated />
using EStoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EStoreAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241101081240_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EStoreAPI.Models.Cellphone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cellphones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Light Green",
                            Image = "https://www.google.com/imgres?q=light%20green%20samsung%20galaxy%20s25%20ultra&imgurl=https%3A%2F%2Fimages.samsung.com%2Fis%2Fimage%2Fsamsung%2Fp6pim%2Fse%2F2401%2Fgallery%2Fse-galaxy-s24-s928-491054-sm-s928blgheub-539439922%3F%24720_576_JPG%24&imgrefurl=https%3A%2F%2Fwww.samsung.com%2Fse%2Fbusiness%2Fsmartphones%2Fgalaxy-s%2Fgalaxy-s24-ultra-512-gb-sm-s928blgheub%2Fbuy%2F&docid=1wBOu4q7cj1gPM&tbnid=cPYWdzd-lbDFTM&vet=12ahUKEwiCgJCm0LqJAxXhAhAIHRWIJ7sQM3oECBcQAA..i&w=720&h=576&hcb=2&ved=2ahUKEwiCgJCm0LqJAxXhAhAIHRWIJ7sQM3oECBcQAA",
                            Model = "Samsung Galaxy s24 Ultra",
                            Price = 22000m
                        },
                        new
                        {
                            Id = 2,
                            Color = "Moonlight Purple",
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.freepik.com%2Fpremium-photo%2Fiphone-15-purple_43528206.htm&psig=AOvVaw1yNDg9B9dhezgxmTMYMm5J&ust=1730533242105000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPjQi-7QuokDFQAAAAAdAAAAABAE",
                            Model = "Iphone 15 Pro",
                            Price = 23000m
                        },
                        new
                        {
                            Id = 3,
                            Color = "Light Blue",
                            Image = "https://www.google.com/imgres?q=Google%20pixel%208%20Pro%20blue&imgurl=https%3A%2F%2Fbsimg.nl%2Fimages%2Fgoogle-pixel-8-pro-256gb-blauw-eu_2.png%2FswX-eXQy8AQuj3MaYMhIvVQbzR8%253D%2Ffit-in%2F0x0%2Ffilters%253Aupscale%2528%2529&imgrefurl=https%3A%2F%2Fwww.gomibo.se%2Fgoogle-pixel-8-pro-eu%2F256gb-bla&docid=_7xgUh0742JgtM&tbnid=J1qYBDRhS5jBpM&vet=12ahUKEwj0hPSJ0bqJAxW3FRAIHaNmNzUQM3oECBwQAA..i&w=325&h=505&hcb=2&itg=1&ved=2ahUKEwj0hPSJ0bqJAxW3FRAIHaNmNzUQM3oECBwQAA",
                            Model = "Google Pixel 8 Pro",
                            Price = 22000m
                        },
                        new
                        {
                            Id = 4,
                            Color = "Grey",
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fsv.gagadget.com%2F450931-hmd-kommer-att-ateruppliva-nokia-3210-den-legendariska-telefonen-fran-1999%2F&psig=AOvVaw3urD6QAvAUzxJBD7jB5xi6&ust=1730533433250000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCODapsbRuokDFQAAAAAdAAAAABAE",
                            Model = "Nokia 3210",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.se%2FHUAWEI-Aperture-SuperCharge-h%25C3%25B6gpresterande-batteri%2Fdp%2FB0BJ7L5DX4&psig=AOvVaw2a_6hjCZ7hhu7ShHmh-IXA&ust=1730533497889000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKjv4eXRuokDFQAAAAAdAAAAABAE",
                            Model = "Huawei Mate 50 Pro",
                            Price = 23000m
                        },
                        new
                        {
                            Id = 6,
                            Color = "Red",
                            Image = "https://www.google.com/imgres?q=one%20plus%20red&imgurl=https%3A%2F%2Foasis.opstatics.com%2Fcontent%2Fdam%2Foasis%2Fpage%2F2023%2Fin%2Fproduct%2F11r%2F11r-red.png&imgrefurl=https%3A%2F%2Fwww.oneplus.in%2F11r%2Fspecs&docid=Cg52G3K2bK1jDM&tbnid=M1MHipRzXvT_XM&vet=12ahUKEwit3NqN0rqJAxX1ExAIHVkHC4sQM3oECGQQAA..i&w=1080&h=1080&hcb=2&ved=2ahUKEwit3NqN0rqJAxX1ExAIHVkHC4sQM3oECGQQAA",
                            Model = "One Plus 11R",
                            Price = 18000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
